# Add your LinkedIn email ID and password.
# *** WARNING: KEEP THIS CONFIG OFFLINE ON YOUR PC AND DO NOT COMMIT/UPLOAD ***
email: cv.kapileswar@gmail.com
password: Lipak@123

# Anti-lock default is False to prevent your PC from sleeping to
# allow bot to run uninterrupted. Set it to True if you wish  to
# disable this functionality.
disableAntiLock: False

# Set to True if you wish to search for remote jobs only.
remote: False

# Set to True if you wish to search for jobs marked as "under 10
# applicants" (default is False).
lessthanTenApplicants: False

# Set to True or False to suit your preference. Multiple True allowed.
experienceLevel:
 internship: False
 entry: True
 associate: True
 mid-senior level: True
 director: False
 executive: False

# Set to True or False to suit your preference. Multiple True allowed.
jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: False
 other: False
 volunteer: False

# Set ONLY one as True to suit your preference.
date:
 all time: True
 month: False
 week: True
 24 hours: False

# Remove hash sign to add positions. You can add as many as you need,
# but preserve formatting
positions:
 - DevOps Engineer
 #- Cloud Engineer
 #- DevOps Engineer
 #- ...

# Remove hash sign to add locations. You can add as many as you need
# including adding 'Remote' as a location but first location must be
# a valid country.
locations:
 - United States
 #- A second location
 #- A third location
 #- ...
 #- Remote

# Set to True if you are residing in the country of job
residentStatus: True

# Distance from the location added above. Allowed values are
# {0, 5, 10, 25, 50, 100}, use only one.
distance: 100

# Optional directory to save logs, does not work sometimes.
# Does not work sometimes, so leave it unchanged.
outputFileDirectory: ~/Documents/Applications/apply_auto/logs/

# Companies you don't want to apply.
companyBlacklist:
 #- company
 #- company2

# Job titles you want to avoid applying. Use it to refine performance of bot.
titleBlacklist:
 #- word1
 #- word2

# Bot will not apply to jobs posted by black listed people.
posterBlacklist:
 #- name1
 #- name2

# Path to your CV/resume and cover letter (remove hash sign). These
# paths often don't work so apply one job manually once,  bot will
# reuse manually uploaded CV for automating the task. Note: Prefer
# a path without spaces, i.e. instead of "Me My" to "MeMy" or "Me_My".
uploads:
 resume: C:\Users\M0359725\Downloads\Kafka_Engineer_Resume_Kapil.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for
 # employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying
 # above, and same with legallyAuthorized.
 requireVisa: True
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # Do you have necessary licenses or certifications required in your
 # profession? E.g. CPA, CA, CFA, professional license
 certifiedProfessional: True
 # We must fill this position urgently. Can you start immediately?
 # (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting or work on-site to this job's location?
 # (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable taking a drug in accordance with local/state laws?
 # (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Do you have security clearance of [xxx] country? (yes/no checkbox)
 securityClearance: False
 # Have you completed the following level of education: DEGREE TYPE? Remove
 # applicable # signs (yes/no checkbox)
 degreeCompleted:
   - Bachelor's Degree
  # - Associate's Degree
  # - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local
 # law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: universityGpa ---------------
universityGpa: 4.0

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum: 65000

# ------------ Additional parameters: languages ---------------
languages:
 english: Professional # Allowed choices { None, Conversational, Professional, Native or bilingual }
 # arabic: Conversational
 # french: Professional

# ------------ Additional parameters: noticePeriod in weeks ---------------
noticePeriod: 1

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only).
# You may add more skills depending on your industry or profession at the bottom.
# Use `unprepared questions.csv` to add more depending on your use case.
# A few samples are added below, you may not need all of these. 'default'
# value will be used as a fall-back input to additional questions.
experience:
 # normal ones
 Linux : 7
 Administrative : 3
 Analyst : 2
 Information Technology: 8
 SQL Server: 5
 AWS : 5
 Azure : 3
 GCP : 5
 kubernetes : 6
 Docker : 5
 Terraform : 6
 Jenkins : 6
 CircleCI : 3
 python: 5
 # default to put for any industry/skill that you did not list
 default: 7

# ------------ Additional parameters: personal info ---------------
personalInfo:
 Pronouns: Mr.
 First Name: Venkata Kapileswar Reddy
 Last Name: Chavva
 Phone Country Code: United States (+1)
 Street address: 3815 Landsdown Ave
 City: Naperville
 State: IL
 Zip: 60564
 Linkedin: www.linkedin.com/in/kapileswar-reddy-a8654134
 #Website: https://www.my-website.com # github/website is interchangeable here
 MessageToManager: "Hi, I am interested to join your organization. Please have a look at my resume. Thank you." # Keep message short and within the quotes. This is a testing feature and may not work.

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Male
 race: None
 veteran: None
 disability: None
 citizenship: no
 clearance: no
